const {deviceState,syncDevice}=require('../../utils/page')
const {recentRecords}=require('../../utils/nativeRecords')
const {requestIeltsLearning}=require('../../utils/ieltsLearning')
const {ensureWeChatSession}=require('../../utils/wechatAuth')
const {learningState,learningReport}=require('../../utils/nativeLearning')
Page({
 data:deviceState({view:'dashboard',title:'今日计划',records:[],total:0,weeklyCount:0,target:6.5,targets:[5,5.5,6,6.5,7,7.5,8,8.5,9],targetIndex:3,user:null,membership:null,code:'',busy:false,error:'',status:'',recordDetail:null,reportRows:[],reportHasMore:false}),
 onLoad(options={}){this.__disposed=false;const view=['records','subscription'].includes(options.view)?options.view:'dashboard';this.setData({view,title:view==='records'?'学习记录':view==='subscription'?'会员':'今日计划'})},
 onShow(){syncDevice(this);this.refresh()},onResize(){syncDevice(this)},onUnload(){this.__disposed=true},
 refresh(){const user=wx.getStorageSync('stemistUser')||null;this.__owner=String(user?.id||'guest');const target=Number(wx.getStorageSync('stemistGoal:'+this.__owner)?.target)||6.5;this.__records=recentRecords();this.setData({user,records:this.__records.slice(0,20),total:this.__records.length,weeklyCount:this.__records.filter(record=>record.submittedAt>Date.now()-7*86400000).length,target,targetIndex:Math.max(0,this.data.targets.indexOf(target)),error:''});if(user&&wx.getStorageSync('stemistSessionToken')){this.loadAccount();this.loadLearning()}},
 async loadLearning(){const expected=this.__owner;try{const state=await learningState();if(this.__disposed||expected!==this.__owner)return;this.__records=[...new Map([...this.__records,...state.records].map(r=>[r.skill+':'+r.id,r])).values()].sort((a,b)=>b.submittedAt-a.submittedAt);this.setData({records:this.__records.slice(0,20),total:this.__records.length,weeklyCount:this.__records.filter(r=>r.submittedAt>Date.now()-7*86400000).length});const local=wx.getStorageSync('stemistGoal:'+this.__owner);if(local?.syncPending)this.syncGoal(local.target);else if(state.profile?.targetBand&&(!local||Date.parse(state.profile.updatedAt)>(local.updatedAt||0))){const target=state.profile.targetBand;wx.setStorageSync('stemistGoal:'+this.__owner,{target,updatedAt:Date.parse(state.profile.updatedAt)});this.setData({target,targetIndex:Math.max(0,this.data.targets.indexOf(target))})}}catch{if(!this.__disposed&&expected===this.__owner)this.setData({status:'本机记录可用，云端记录暂未连接'})}},
 async loadAccount(){const expected=this.__owner;try{const payload=await requestIeltsLearning('/api/me',undefined,{method:'GET'});if(!this.__disposed&&this.__owner===expected)this.setData({membership:payload.user?.membership||payload.membership||null})}catch{if(!this.__disposed)this.setData({status:'本机记录可用，账号同步暂未完成'})}},
 chooseTarget(event){const targetIndex=Number(event.detail.value),target=this.data.targets[targetIndex];if(!target)return;wx.setStorageSync('stemistGoal:'+this.__owner,{target,updatedAt:Date.now(),syncPending:true});this.setData({targetIndex,target,status:'目标已保存'});this.syncGoal(target)},
 syncGoal(target){const expected=this.__owner;if(expected==='guest'||!wx.getStorageSync('stemistSessionToken'))return;this.__goalQueue=(this.__goalQueue||Promise.resolve()).catch(()=>{}).then(async()=>{if(this.__disposed||expected!==this.__owner||target!==this.data.target)return;try{const result=await requestIeltsLearning('/api/learning/profile',{targetBand:target},{method:'PATCH'});if(!this.__disposed&&expected===this.__owner&&target===this.data.target){wx.setStorageSync('stemistGoal:'+expected,{target,updatedAt:Date.parse(result.profile?.updatedAt)||Date.now(),syncPending:false});this.setData({status:'目标已同步'})}}catch{if(!this.__disposed&&expected===this.__owner)this.setData({status:'目标已保存在本机，稍后可同步'})}})},
 openSkill(event){const module=event.currentTarget.dataset.module;if(['listening','reading','writing','speaking'].includes(module))wx.navigateTo({url:'/pages/ielts/library?module='+module})},
 more(){this.setData({records:this.__records.slice(0,Math.min(200,this.data.records.length+20))})},
 openRecord(event){const record=this.__records[Number(event.currentTarget.dataset.index)];if(!record)return;if(record.cloud)return this.showReport(record);if(record.skill==='writing-full')return wx.navigateTo({url:'/pages/ielts/writing-full?pairId='+encodeURIComponent(record.taskId)});if(record.skill==='exam'&&record.id.startsWith('mini-exam-'))return wx.navigateTo({url:'/pages/ielts/exam?examKey='+encodeURIComponent(record.id)});if(record.taskId&&['listening','reading','writing','speaking'].includes(record.skill))return wx.navigateTo({url:'/pages/ielts/'+record.skill+'?taskId='+encodeURIComponent(record.taskId)+(record.section?'&section='+record.section:'' )});if(record.paperId)return wx.navigateTo({url:'/pages/stem/paper?paperId='+encodeURIComponent(record.paperId)+'&subject='+encodeURIComponent(record.subjectCode)+'&routeId='+encodeURIComponent(record.routeId)+'&mode='+encodeURIComponent(record.mode||'past-paper-practice')})},
 async showReport(record){if(this.data.busy)return;const expected=this.__owner;this.setData({busy:true,error:''});try{const report=await learningReport(record.id);if(this.__disposed||expected!==this.__owner)return;this.__report=report;const feedback=[report.result?.feedback,report.feedback?.text,report.feedback?.feedback,report.result?.reportText].find(value=>typeof value==='string')||'';this.setData({recordDetail:{title:record.title,band:record.band,answerAvailable:report.result?.answerAvailable===true,correct:report.result?.correct,total:report.result?.scoredTotal||report.result?.total,feedback},reportRows:(report.result?.details||[]).slice(0,10),reportHasMore:(report.result?.details||[]).length>10})}catch(e){if(!this.__disposed)this.setData({error:e.message})}finally{if(!this.__disposed)this.setData({busy:false})}},
 closeReport(){this.__report=null;this.setData({recordDetail:null,reportRows:[],reportHasMore:false})},
 moreReport(){const all=this.__report?.result?.details||[],count=this.data.reportRows.length+10;this.setData({reportRows:all.slice(0,count),reportHasMore:count<all.length})},
 inputCode(event){this.setData({code:String(event.detail.value||'').slice(0,100),error:''})},
 async redeem(){if(this.data.busy||!this.data.code.trim())return;this.setData({busy:true,error:''});try{await requestIeltsLearning('/api/redeem',{code:this.data.code.trim()});if(!this.__disposed){this.setData({code:'',status:'已提交激活'});await this.loadAccount()}}catch(e){if(!this.__disposed)this.setData({error:e.message})}finally{if(!this.__disposed)this.setData({busy:false})}},
 async signIn(){if(this.data.busy)return;this.setData({busy:true,error:''});try{await ensureWeChatSession({silent:false});if(!this.__disposed)this.refresh()}catch(e){if(!this.__disposed)this.setData({error:e.message||'微信登录未完成'})}finally{if(!this.__disposed)this.setData({busy:false})}},
 account(){wx.navigateTo({url:'/pages/account/auth'})},
 back(){wx.navigateBack()}
})
