const {deviceState,syncDevice}=require('../../utils/page')
const {loadIeltsContent,catalogPage,subscribeIeltsContent}=require('../../utils/ieltsContent')
const {libraryUnits}=require('../../utils/ieltsUnits')
const {writingPairs}=require('../../utils/ieltsWriting')
const {topicDirectory,topicIcon}=require('../../utils/ieltsTopics')
const TITLES={listening:'Listening',reading:'Reading',writing:'Writing',speaking:'Speaking'}
Page({
 data:deviceState({module:'listening',title:'Listening',loading:true,catalogLoaded:false,error:'',items:[],total:0,page:0,pageCount:0,query:'',books:[],book:0,bookIndex:0,scope:'paper',scopes:[{id:'paper',label:'整套'},{id:'section',label:'分段'},{id:'topic',label:'主题'}],topics:[],topicItems:[],topic:'',topicIndex:0}),
 onLoad(options={}){this.__disposed=false;this.__generation=0;const module=TITLES[options.module]?options.module:'listening';this.setData({module,title:TITLES[module],...(module==='writing'?{scopes:[{id:'paper',label:'单题'},{id:'pair',label:'完整写作'},{id:'topic',label:'主题'}]}:module==='speaking'?{scope:'topic',scopes:[{id:'topic',label:'主题'},{id:'paper',label:'整套'}]}:{})});this.__unsubscribe=subscribeIeltsContent?.(data=>{if(!this.__disposed){this.__generation++;this.applyCatalog(data);this.setData({loading:false,error:''})}});this.load()},
 onShow(){syncDevice(this)},onResize(){syncDevice(this)},onUnload(){this.__disposed=true;this.__generation++;this.__unsubscribe?.();clearTimeout(this.__searchTimer)},
 applyCatalog(data){if(!Array.isArray(data[this.data.module]))return;this.__tasks=data[this.data.module];const books=[{value:0,label:'全部来源'},...(this.__tasks.some(t=>t.sourceKind==='public-topic'||t.source==='Public topics')?[{value:'public',label:'公开话题'}]:[]),...[...new Set(this.__tasks.map(t=>t.book).filter(Boolean))].sort((a,b)=>b-a).map(value=>({value,label:'Cambridge '+value}))];const bookIndex=Math.max(0,books.findIndex(b=>b.value===this.data.book));this.setData({books,bookIndex,book:books[bookIndex].value,catalogLoaded:true});this.render()},
 async load(refresh=false){const generation=++this.__generation;this.setData({loading:!this.__tasks,error:''});try{const data=await loadIeltsContent({refresh:refresh===true});if(this.__disposed||generation!==this.__generation)return;this.applyCatalog(data)}catch(e){if(!this.__disposed)this.setData({error:e.message})}finally{if(!this.__disposed&&generation===this.__generation)this.setData({loading:false});if(refresh===true)wx.stopPullDownRefresh?.()}},
 reload(){return this.load(true)},onPullDownRefresh(){return this.load(true)},
 render(){if(!this.__tasks)return;this.__units=this.data.module==='writing'&&this.data.scope==='pair'?writingPairs(this.__tasks).map(pair=>({...pair,source:'Cambridge IELTS',minutes:60,questions:[],questionCount:0,kind:'pair'})):libraryUnits(this.__tasks,this.data.scope,this.data.topic);const topics=topicDirectory(this.__tasks,this.data),directory=this.data.scope==='topic'&&!this.data.topic,topicPages=Math.ceil(topics.length/20),topicPage=Math.min(this.data.page,Math.max(0,topicPages-1));const selected=topics.find(t=>t.key===this.data.topic);this.setData({...catalogPage(this.__units,this.data),...(directory?{items:[],page:topicPage,pageCount:topicPages,topicItems:topics.slice(topicPage*20,(topicPage+1)*20)}:{topicItems:[]}),topics,topicLabel:selected?.label||this.data.topic,topicIcon:selected?.icon||topicIcon(this.data.topic),topicEmoji:selected?.emoji||''})},
 chooseScope(event){const scope=String(event.currentTarget.dataset.scope||'');if(!this.data.scopes.some(s=>s.id===scope))return;this.setData({scope,page:0,topic:'',topicIndex:0});this.render()},
 chooseTopic(event){const key=event.currentTarget?.dataset?.key||this.data.topics[Number(event.detail?.value)]?.key;if(!this.data.topics.some(t=>t.key===key))return;this.setData({topic:key,page:0});this.render()},
 clearTopic(){this.setData({topic:'',page:0});this.render()},
 search(event){this.setData({query:String(event.detail.value||''),page:0});clearTimeout(this.__searchTimer);this.__searchTimer=setTimeout(()=>{if(!this.__disposed)this.render()},180)},
 chooseBook(event){const bookIndex=Number(event.detail.value),book=this.data.books[bookIndex]?.value||0;this.setData({bookIndex,book,page:0});this.render()},
 previous(){this.setData({page:Math.max(0,this.data.page-1)});this.render();wx.pageScrollTo?.({scrollTop:0,duration:0})},
 next(){if(this.data.page+1>=this.data.pageCount)return;this.setData({page:this.data.page+1});this.render();wx.pageScrollTo?.({scrollTop:0,duration:0})},
 open(event){const id=String(event.currentTarget.dataset.id||''),unit=this.__units?.find(t=>t.id===id);if(!unit)return;const url=unit.kind==='pair'?'/pages/ielts/writing-full?pairId='+encodeURIComponent(id):`/pages/ielts/${this.data.module}?taskId=${encodeURIComponent(unit.baseTaskId||id)}`+(unit.section?'&section='+unit.section:'');wx.navigateTo({url,fail:()=>this.setData({error:'试题未能打开，请重试。'})})},
 back(){wx.navigateBack({fail:()=>wx.reLaunch({url:'/pages/practice/index?category=ielts'})})}
})
